# Generated by Django 3.0.1 on 2020-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200102_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='social_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
