# Generated by Django 3.0.1 on 2019-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_spaces'),
        ('account', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='like',
            field=models.ManyToManyField(through='account.Likes', to='space.Spaces'),
        ),
    ]
