# Generated by Django 3.0.1 on 2019-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
