# Generated by Django 3.0.1 on 2019-12-26 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_hosts'),
        ('space', '0002_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_intro', models.CharField(max_length=200)),
                ('long_intro', models.TextField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Hosts')),
            ],
            options={
                'db_table': 'spaces',
            },
        ),
    ]
