# Generated by Django 3.0.1 on 2020-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20200101_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='min_guest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='spaces',
            name='min_time',
            field=models.CharField(max_length=10),
        ),
    ]
