# Generated by Django 3.0.1 on 2019-12-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.Spaces')),
                ('space_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.Space_Categories')),
            ],
            options={
                'db_table': 'categories_space',
            },
        ),
    ]
