# Generated by Django 3.0.1 on 2019-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_spaces_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
