# Generated by Django 3.0.1 on 2019-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='space_image',
            field=models.URLField(max_length=2500),
        ),
    ]
